### ISSUE TITLE
5.1.3 Employees Pages

### ISSUE THREAD

**Issue by personryan** [personryan/ICT-2101-P4-1#46]
11/11/22: Start of employee pages prototype in figma

**Comment by personryan** [comment]
18/11/22: Implemented some pages




![Image](https://user-images.githubusercontent.com/90229655/202695089-17cde59b-22ad-4d9a-9ade-b612991412c2.png)

**Comment by ShaunVSIT** [comment]
Staff pages completed on 24/11, overran deadline due to change in state flow and system considerations.



![Image](https://user-images.githubusercontent.com/91268180/204007006-a2febf56-5224-439d-bc6e-667b4667a160.png)



![Image](https://user-images.githubusercontent.com/91268180/204007021-d0f9dc44-b6d0-4861-87b1-8f1be6f07ec6.png)



![Image](https://user-images.githubusercontent.com/91268180/204007038-c9542846-d301-46a3-ba01-033315bbb5dd.png)



![Image](https://user-images.githubusercontent.com/91268180/204007051-185ab610-7a48-48b4-8c31-232ddb30ca87.png)



![Image](https://user-images.githubusercontent.com/91268180/204007076-ad491ee9-cc83-4868-8a2c-b5f0b037ae2c.png)

**Comment by personryan** [comment]
26/11/22: the pages looks good will be closing the issue
