### ISSUE TITLE
5.1.1 Manager Pages

### ISSUE THREAD

**Issue by Uygnis** [personryan/ICT-2101-P4-1#57]
11/11: Complete interactable Manager pages by 18/11/22

**Comment by ShaunVSIT** [comment]
Manager pages completed on 24/11,  overran deadline due to change in state flow and system considerations



![Image](https://user-images.githubusercontent.com/91268180/204006645-90bf2806-ee9b-4a44-a7f1-e766833bbef7.png)


![Image](https://user-images.githubusercontent.com/91268180/204006673-48e3d669-4064-4c4b-b015-ca748e17a770.png)



![Image](https://user-images.githubusercontent.com/91268180/204006688-645d35e3-ed5f-438a-bf2d-8f86c83b3ce6.png)




![Image](https://user-images.githubusercontent.com/91268180/204006708-4f682f7f-7497-47e8-8aa2-3bb0ecb360cb.png)



![Image](https://user-images.githubusercontent.com/91268180/204006720-a055862d-0fac-41c1-8379-92bb80bf93a5.png)

**Comment by Uygnis** [comment]
@ShaunVSIT looks good
